language: node_js
node_js:
- '10'
cache: npm
jobs:
  include:
    - stage: install
      script:
        - npm install -g @angular/cli
        - npm install -g firebase-tools
    - stage: test
      script:
        - ng lint
        - ng test --code-coverage=true --no-watch --no-progress --browsers ChromeHeadlessCI
    - stage: deploy
      script:
        - ng build --prod
        - firebase deploy --token APP_TOKEN
stages:
  - name: install
  - name: test
  - name: deploy
    if: branch = master
