language: node_js
node_js:
- '10'
cache: npm
git:
  depth: false
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
  - ng lint
  - ng test --code-coverage=true --no-watch --no-progress --browsers ChromeHeadlessCI
  - ng build --prod
after_success:
  if: branch = master
    - npm version minor
    - git push origin master --tag
  if: NOT branch = master AND push
    - npm update patch
    - git push --tag
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $APP_TOKEN
