language: node_js
node_js:
- '10'
cache: npm
git:
  depth: false
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
  - ng lint
  - ng test --code-coverage=true --no-watch --no-progress --browsers ChromeHeadlessCI
  - ng build --prod
after_success:
  $TRAVIS_BRANCH = "master"
    - npm version patch
    - git push origin master --tag
  $TRAVIS_BRANCH != "master"
    - npm version patch
    - git push --tag
deploy:
  cleanup: false
  provider: firebase
  token:
    secure: $APP_TOKEN
