language: node_js
node_js:
- '10'
cache: npm
jobs:
  include:
    - stage: Install
      script:
        - npm install -g @angular/cli
        - npm install -g firebase-tools
    - stage: Tests
      script:
        - ng lint
        - ng test --code-coverage=true --no-watch --no-progress --browsers ChromeHeadlessCI
    - stage: Deploy
      script:
        - if [ $TRAVIS_BRANCH = "master" ]; then npm version minor; fi;
        - if [ $TRAVIS_BRANCH != "master" ] & [ $TRAVIS_PULL_REQUEST = "true" ]; then npm version patch; fi;
        - git push -f -q https://chicojunior:$GH_TOKEN@github.com/chicojunior/epam-angular-mentoring;
    - stage: Publish
      script:
        - if [ $TRAVIS_BRANCH = "master" ]; then firebase deploy --token $APP_TOKEN;
