language: node_js
node_js:
- '10'
cache: npm
git:
  depth: false
jobs:
  include:
    - stage: Tests
      script:
        - npm install -g @angular/cli
        - ng lint
        - ng test --code-coverage=true --no-watch --no-progress --browsers ChromeHeadlessCI
    - stage: Update
      script:
        - branch=$(git rev-parse --abbrev-ref HEAD);
        - echo $branch;
        - if [ $TRAVIS_BRANCH = "master" ]; then npm version minor; git push -f https://$GH_USER:$GH_TOKEN@github.com/$GH_USER/epam-angular-mentoring HEAD:master; fi;
        - if [ $TRAVIS_BRANCH != "master" ] & [ $TRAVIS_PULL_REQUEST = "true" ]; then npm version patch; fi;
    - stage: Publish
      script:
        - npm install -g firebase-tools;
        - if [ $TRAVIS_BRANCH = "master" ]; then firebase deploy --token $APP_TOKEN;
