language: node_js
node_js:
- '10'
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
  - ng lint
  - ng test --no-watch --no-progress --browsers ChromeHeadlessCI
  - ng build --prod
after_success:
  - firebase deploy --token 1//0cI6gmhHUemFyCgYIARAAGAwSNwF-L9IrC42zsC-0ecCwuWmf-Ng-vzFulzWlSEjb_pfSHBEE9gtKgDspYIOuB5MFHUe5GlRUCCA
