language: node_js
node_js:
- '10'
jobs:
  include:
    - stage: Tests
      script:
        - npm install -g @angular/cli;
        - ng lint;
        - ng test --code-coverage=true --no-watch --no-progress --browsers ChromeHeadlessCI;
    - stage: Deploy
      script:
        - npm install -g firebase-tools;
        - ng build --prod;
        - if [ $TRAVIS_BRANCH = "master" ]; then firebase deploy --token $APP_TOKEN; fi;
