language: node_js
node_js:
- '10'
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
  - ng lint
  - ng test --no-watch --no-progress --browsers ChromeHeadlessCI
  - ng build --prod
deploy:
  provider: firebase
  token:
    secure: APP_TOKEN
  on:
    branch: master
